import os

root_dir = r"c:\Users\sales\axtra template\built_templates"
output_file = r"c:\Users\sales\axtra template\index.html"

templates = []
if os.path.exists(root_dir):
    for item in os.listdir(root_dir):
        if os.path.isdir(os.path.join(root_dir, item)):
            templates.append(item)

html_content = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Axtra Templates Gallery</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
    <style>
        :root {
            --primary: #2563eb;
            --bg: #f8fafc;
            --surface: #ffffff;
            --text: #1e293b;
            --text-muted: #64748b;
            --border: #e2e8f0;
        }
        body {
            font-family: 'Inter', sans-serif;
            background-color: var(--bg);
            color: var(--text);
            margin: 0;
            padding: 0;
            line-height: 1.5;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
        }
        header {
            text-align: center;
            margin-bottom: 3rem;
            padding-bottom: 2rem;
            border-bottom: 1px solid var(--border);
        }
        h1 {
            font-size: 2.5rem;
            margin-bottom: 0.5rem;
            color: var(--text);
        }
        p.subtitle {
            color: var(--text-muted);
            font-size: 1.1rem;
        }
        .grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: 1.5rem;
        }
        .card {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 8px;
            overflow: hidden;
            transition: transform 0.2s, box-shadow 0.2s;
            text-decoration: none;
            color: inherit;
            display: flex;
            flex-direction: column;
        }
        .card:hover {
            transform: translateY(-4px);
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
            border-color: var(--primary);
        }
        .card-body {
            padding: 1.5rem;
        }
        .card-title {
            font-size: 1.1rem;
            font-weight: 600;
            margin: 0 0 0.5rem 0;
            text-transform: capitalize;
        }
        .card-meta {
            font-size: 0.85rem;
            color: var(--text-muted);
            font-family: monospace;
        }
        .tag {
            display: inline-block;
            padding: 0.25rem 0.5rem;
            background: #e0f2fe;
            color: #0369a1;
            border-radius: 4px;
            font-size: 0.75rem;
            font-weight: 600;
            margin-top: 1rem;
            text-transform: uppercase;
        }
        footer {
            text-align: center;
            margin-top: 4rem;
            color: var(--text-muted);
            font-size: 0.9rem;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Axtra Templates</h1>
            <p class="subtitle">Collection of generated website templates</p>
        </header>
        
        <div class="grid">
"""

for template in sorted(templates):
    # Parse name: type_style_hash
    parts = template.split('_')
    if len(parts) >= 3:
        category = parts[0]
        style = parts[1]
        hash_id = parts[-1]
        display_name = f"{category.title()} {style.title()}"
    else:
        display_name = template
        category = "Unknown"
        hash_id = ""

    link = f"built_templates/{template}/index.html"
    
    html_content += f"""
            <a href="{link}" class="card" target="_blank">
                <div class="card-body">
                    <h2 class="card-title">{display_name}</h2>
                    <div class="card-meta">ID: {hash_id}</div>
                    <span class="tag">{category}</span>
                </div>
            </a>
    """

html_content += """
        </div>
        
        <footer>
            Generated by Axtra Template Engine
        </footer>
    </div>
</body>
</html>
"""

with open(output_file, "w") as f:
    f.write(html_content)

print(f"Index page generated at {output_file}")
